# Generated by Django 6.1.1 on 2026-09-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_company_created_at_remove_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_check', models.BooleanField(default=True)),
                ('paper_check', models.BooleanField(default=True)),
                ('accident_history', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vehicle')),
            ],
        ),
    ]
