# Generated by Django 6.1.1 on 2026-09-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_vehicleverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleverification',
            name='odometer_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicleverification',
            name='accident_history',
            field=models.BooleanField(default=False, verbose_name='Accident?'),
        ),
        migrations.AlterField(
            model_name='vehicleverification',
            name='engine_check',
            field=models.BooleanField(default=True, verbose_name='Engine OK?'),
        ),
        migrations.AlterField(
            model_name='vehicleverification',
            name='paper_check',
            field=models.BooleanField(default=True, verbose_name='Papers OK?'),
        ),
        migrations.AlterField(
            model_name='vehicleverification',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='marketplace.vehicle'),
        ),
    ]
